language: node_js

node_js:
  - "4"

cache:
  directories:
    - "node_modules"

install:
  echo "------------ before install"

before_install:
  - npm install

script:
  #- pwd
  - node -v
  - ./node_modules/gulp/bin/gulp.js -v
  - ./node_modules/gulp/bin/gulp.js build
